<?php

namespace App\Evostorm\Enums;

/**
 * Description of RoleEnum
 *
 * @author damian
 */
abstract class GameConfigEnum {

    const MAP_X_SIZE = 1;
    const MAP_Y_SIZE = 2;
    const USER_MAP_WIDTH = 3;
    const USER_MAP_HEIGHT = 4;
    const RESOURCE_GOLD_STARTING_AMOUNT = 5;
    const RESOURCE_URANIUM_STARTING_AMOUNT = 6;
    const RESOURCE_FOOD_STARTING_AMOUNT = 7;
    const RESOURCE_WORKFORCE_STARTING_AMOUNT = 8;
    const RESOURCE_KEGRUM_STARTING_AMOUNT = 9;
    const RESOURCE_GOLD_STARTING_INCOME_AMOUNT = 10;
    const RESOURCE_URANIUM_STARTING_INCOME_AMOUNT = 11;
    const RESOURCE_FOOD_STARTING_INCOME_AMOUNT = 12;
    const RESOURCE_WORKFORCE_STARTING_INCOME_AMOUNT = 13;
    const RESOURCE_KEGRUM_STARTING_INCOME_AMOUNT = 14;
    const RESOURCE_GOLD_STARTING_OUTCOME_AMOUNT = 15;
    const RESOURCE_URANIUM_STARTING_OUTCOME_AMOUNT = 16;
    const RESOURCE_FOOD_STARTING_OUTCOME_AMOUNT = 17;
    const RESOURCE_WORKFORCE_STARTING_OUTCOME_AMOUNT = 18;
    const RESOURCE_KEGRUM_STARTING_OUTCOME_AMOUNT = 19;
    const USER_MAP_TILE_RADIUS = 20;

}
